trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    dotnet build ./bicep/main.bicep
  displayName: 'Build Bicep templates'

- script: |
    if ! command -v dotnet &> /dev/null
    then
        echo ".NET SDK not found, installing..."
        wget -q https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y apt-transport-https
        sudo apt-get update
        sudo apt-get install -y dotnet-sdk-6.0
    fi
  displayName: 'Install .NET SDK 6.0 if not installed'

- script: |
    az group create --name staticweb --location West Europe
    az deployment group create --resource-group staticweb --template-file ./bicep/main.bicep --parameters ./bicep/parameters.json
  displayName: 'Deploy Bicep templates'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Invoke-Pester -Path 'tests'
